version: "3.9"

secrets:
  postgrespassword:
    file: ./secrets/.postgrespassword
  databaseurl:
    file: ./secrets/.databaseurl
  secretkeybase:
    file: ./secrets/.secretkeybase

services:
  db:
    image: postgres:15.2
    healthcheck:
      test: [ "CMD", "pg_isready", "--username=postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - ${POSTGRES_PORT:-5432}
    secrets:
      - postgrespassword
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgrespassword
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    image: ${WEB_IMAGE:-ghcr.io/hans-pistor/kanban:latest}
    depends_on:
      - db
    command: >
      bash -c "bin/migrate && bin/server"
    deploy:
      replicas: ${WEB_REPLICAS:-1}
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    secrets:
      - secretkeybase
      - databaseurl
    environment:
      - DATABASE_URL_FILE=/run/secrets/databaseurl
      - SECRET_KEY_BASE_FILE=/run/secrets/secretkeybase
      - PHX_HOST="localhost"
    ports:
      - 4000:4000

volumes:
  db_data:
